[definition]
max_abstract_number = 1
required_fields = ['Keywords', 'Title', 'Description', 'Focus']

[distinction]
max_abstract_number = 2
required_fields = ['Distinguishing Features']

[questions]
required_fields = ['Open Questions']

[trends]
max_abstract_number = 2
older_cutoff = 2010
recent_cutoff = 2023
required_fields = [
                 'Emerging Themes',
                 'Emerging Methodological Approaches',
                 'Declining Themes',
                 'Declining Methodological Approaches'
                 ]

[dimensions]
max_abstract_number = 2
older_cutoff = 2010
recent_cutoff = 2023
required_fields = [
                'Dimension 1 - Appliedness', 'Dimension 2 - Modality',
                'Dimension 3 - Spatiotemporal Scale',
                'Dimension 4 - Cognitive Complexity', 'Dimension 5 - Species',
                'Dimension 6 - Theory Engagement',
                'Dimension 7 - Theory Scope',
                'Dimension 8 - Methodological Approach',
                'Dimension 9 - Interdisciplinarity'
        ]

[llm]
temperature = 0.0
model_name = 'orca-mini:13b'
delay = 2.0
retries = 2

